repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: |
            (?x)^(
                bin/.*|
                node_modules/.*
                .yarn/.*
            )$
      - id: check-symlinks
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                bin/.*|
                node_modules/.*
                .yarn/.*
            )$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: |
            (?x)^(
                bin/.*|
                node_modules/.*
                .yarn/.*
            )$
